# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

from __future__ import annotations
import os
import sys
import ctypes
from dataclasses import dataclass
import enum
import struct
import contextlib
import datetime
import threading
import itertools
import traceback
import typing
import platform


# Used for default argument values
_DEFAULT = object() # type: typing.Any

import ctypes
import struct

class _UniffiRustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_uint64),
        ("len", ctypes.c_uint64),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def default():
        return _UniffiRustBuffer(0, 0, None)

    @staticmethod
    def alloc(size):
        return _uniffi_rust_call(_UniffiLib.ffi_janjacord_mobile_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return _uniffi_rust_call(_UniffiLib.ffi_janjacord_mobile_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return _uniffi_rust_call(_UniffiLib.ffi_janjacord_mobile_rustbuffer_free, self)

    def __str__(self):
        return "_UniffiRustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def alloc_with_builder(*args):
        """Context-manger to allocate a buffer using a _UniffiRustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = _UniffiRustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consume_with_stream(self):
        """Context-manager to consume a buffer using a _UniffiRustBufferStream.

        The _UniffiRustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = _UniffiRustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError(f"junk data left in buffer at end of consume_with_stream {s.remaining()}")
        finally:
            self.free()

    @contextlib.contextmanager
    def read_with_stream(self):
        """Context-manager to read a buffer using a _UniffiRustBufferStream.

        This is like consume_with_stream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `_UniffiRustBuffer` data.
        """
        s = _UniffiRustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError(f"junk data left in buffer at end of read_with_stream {s.remaining()}")

class _UniffiForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "_UniffiForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class _UniffiFfiConverterByRefBytes:
    """Zero-copy converter for `&[u8]` / `[ByRef] bytes` arguments.

    Only `lower` and `check_lower` are valid — zero-copy byte buffers only
    flow foreign -> Rust, and only in argument position. `lift`, `read`, and
    `write` have no sound implementation here.

    CPython `bytes` objects are immutable and their internal buffer doesn't
    move for the lifetime of the object; the caller must keep the source
    `bytes` alive for the duration of the FFI call.
    """

    @staticmethod
    def check_lower(value):
        # Tighter than `bytes-like`: `lower` uses `ctypes.c_char_p` which only
        # accepts `bytes`/`None`, so fail fast with a matching check.
        if not isinstance(value, bytes):
            raise TypeError("a bytes object is required, not {!r}".format(type(value).__name__))

    @staticmethod
    def lower(value):
        fb = _UniffiForeignBytes()
        if len(value) == 0:
            fb.len = 0
            fb.data = None
        else:
            fb.len = len(value)
            fb.data = ctypes.cast(ctypes.c_char_p(value), ctypes.POINTER(ctypes.c_char))
        return fb

    @staticmethod
    def lift(value):
        raise NotImplementedError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")

    @staticmethod
    def read(buf):
        raise NotImplementedError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    @staticmethod
    def write(value, buf):
        raise NotImplementedError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")


class _UniffiRustBufferStream:
    """
    Helper for structured reading of bytes from a _UniffiRustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def read_i8(self):
        return self._unpack_from(1, ">b")

    def read_u8(self):
        return self._unpack_from(1, ">B")

    def read_i16(self):
        return self._unpack_from(2, ">h")

    def read_u16(self):
        return self._unpack_from(2, ">H")

    def read_i32(self):
        return self._unpack_from(4, ">i")

    def read_u32(self):
        return self._unpack_from(4, ">I")

    def read_i64(self):
        return self._unpack_from(8, ">q")

    def read_u64(self):
        return self._unpack_from(8, ">Q")

    def read_float(self):
        v = self._unpack_from(4, ">f")
        return v

    def read_double(self):
        return self._unpack_from(8, ">d")

class _UniffiRustBufferBuilder:
    """
    Helper for structured writing of bytes into a _UniffiRustBuffer.
    """

    def __init__(self):
        self.rbuf = _UniffiRustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, num_bytes):
        if self.rbuf.len + num_bytes > self.rbuf.capacity:
            self.rbuf = _UniffiRustBuffer.reserve(self.rbuf, num_bytes)
        yield None
        self.rbuf.len += num_bytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            packed = struct.pack(format, value)
            if size > 0:
                ctypes.memmove(ctypes.addressof(self.rbuf.data.contents) + self.rbuf.len, packed, size)
    
    def write(self, value):
        length = len(value)
        with self._reserve(length):
            if length > 0:
                ctypes.memmove(ctypes.addressof(self.rbuf.data.contents) + self.rbuf.len, value, length)

    def write_i8(self, v):
        self._pack_into(1, ">b", v)

    def write_u8(self, v):
        self._pack_into(1, ">B", v)

    def write_i16(self, v):
        self._pack_into(2, ">h", v)

    def write_u16(self, v):
        self._pack_into(2, ">H", v)

    def write_i32(self, v):
        self._pack_into(4, ">i", v)

    def write_u32(self, v):
        self._pack_into(4, ">I", v)

    def write_i64(self, v):
        self._pack_into(8, ">q", v)

    def write_u64(self, v):
        self._pack_into(8, ">Q", v)

    def write_float(self, v):
        self._pack_into(4, ">f", v)

    def write_double(self, v):
        self._pack_into(8, ">d", v)

    def write_c_size_t(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class _UniffiRustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", _UniffiRustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_UNEXPECTED_ERROR = 2

    @staticmethod
    def default():
        return _UniffiRustCallStatus(code=_UniffiRustCallStatus.CALL_SUCCESS, error_buf=_UniffiRustBuffer.default())

    def __str__(self):
        if self.code == _UniffiRustCallStatus.CALL_SUCCESS:
            return "_UniffiRustCallStatus(CALL_SUCCESS)"
        elif self.code == _UniffiRustCallStatus.CALL_ERROR:
            return "_UniffiRustCallStatus(CALL_ERROR)"
        elif self.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
            return "_UniffiRustCallStatus(CALL_UNEXPECTED_ERROR)"
        else:
            return "_UniffiRustCallStatus(<invalid code>)"

def _uniffi_rust_call(fn, *args):
    # Call a rust function
    return _uniffi_rust_call_with_error(None, fn, *args)

def _uniffi_rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the _UniffiConverter for the error class that corresponds to the result.
    call_status = _UniffiRustCallStatus.default()

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    _uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def _uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == _UniffiRustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == _UniffiRustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("_uniffi_rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
        # When the rust code sees a panic, it tries to construct a _UniffiRustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = _UniffiFfiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid _UniffiRustCallStatus code: {}".format(
            call_status.code))

def _uniffi_trait_interface_call(call_status, make_call, write_return_value):
    try:
        return write_return_value(make_call())
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))

def _uniffi_trait_interface_call_with_error(call_status, make_call, write_return_value, error_type, lower_error):
    try:
        try:
            return write_return_value(make_call())
        except error_type as e:
            call_status.code = _UniffiRustCallStatus.CALL_ERROR
            call_status.error_buf = lower_error(e)
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))
# Initial value and increment amount for handles. 
# These ensure that Python-generated handles always have the lowest bit set
_UNIFFI_HANDLEMAP_INITIAL = 1
_UNIFFI_HANDLEMAP_DELTA = 2

class _UniffiHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._map = {}  # type: Dict[Handle, Any]
        self._lock = threading.Lock()
        self._counter = _UNIFFI_HANDLEMAP_INITIAL

    def insert(self, obj):
        with self._lock:
            return self._insert(obj)

    """Low-level insert, this assumes `self._lock` is held."""
    def _insert(self, obj):
        handle = self._counter
        self._counter += _UNIFFI_HANDLEMAP_DELTA
        self._map[handle] = obj
        return handle

    def get(self, handle):
        try:
            with self._lock:
                return self._map[handle]
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.get: Invalid handle {handle}")

    def clone(self, handle):
        try:
            with self._lock:
                obj = self._map[handle]
                return self._insert(obj)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.clone: Invalid handle {handle}")

    def remove(self, handle):
        try:
            with self._lock:
                return self._map.pop(handle)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.remove: Invalid handle: {handle}")

    def __len__(self):
        return len(self._map)
# Types conforming to `_UniffiConverterPrimitive` pass themselves directly over the FFI.
class _UniffiConverterPrimitive:
    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return value

class _UniffiConverterPrimitiveInt(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))

class _UniffiConverterPrimitiveFloat(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))

# Helper class for wrapper types that will always go through a _UniffiRustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class _UniffiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consume_with_stream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code, and the FFI Function declarations.
# Define some ctypes FFI types that we use in the library

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
_UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int8)

def _uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_uint64, return_type, _UniffiRustCallStatus)

def _uniffi_load_indirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("janjacord_mobile")
    path = os.path.join(os.path.dirname(__file__), libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def _uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 30
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_janjacord_mobile_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def _uniffi_check_api_checksums(lib):
    if lib.uniffi_janjacord_mobile_checksum_func_add_member() != 52177:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_janjacord_mobile_checksum_func_argon2id() != 13289:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_janjacord_mobile_checksum_func_create_group() != 33565:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_janjacord_mobile_checksum_func_decrypt() != 7107:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_janjacord_mobile_checksum_func_encrypt() != 63996:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_janjacord_mobile_checksum_func_export_group() != 5589:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_janjacord_mobile_checksum_func_generate_key_package() != 36306:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_janjacord_mobile_checksum_func_import_group() != 54702:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_janjacord_mobile_checksum_func_join_group() != 64575:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_janjacord_mobile_checksum_func_process_commit() != 19615:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_janjacord_mobile_checksum_func_remove_member() != 3261:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniffiLib = _uniffi_load_indirect()
_UniffiLib.ffi_janjacord_mobile_rustbuffer_alloc.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_janjacord_mobile_rustbuffer_alloc.restype = _UniffiRustBuffer
_UniffiLib.ffi_janjacord_mobile_rustbuffer_from_bytes.argtypes = (
    _UniffiForeignBytes,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_janjacord_mobile_rustbuffer_from_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_janjacord_mobile_rustbuffer_free.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_janjacord_mobile_rustbuffer_free.restype = None
_UniffiLib.ffi_janjacord_mobile_rustbuffer_reserve.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_janjacord_mobile_rustbuffer_reserve.restype = _UniffiRustBuffer
_UniffiLib.ffi_janjacord_mobile_uniffi_contract_version.argtypes = (
)
_UniffiLib.ffi_janjacord_mobile_uniffi_contract_version.restype = ctypes.c_uint32
_UniffiLib.uniffi_janjacord_mobile_checksum_func_add_member.argtypes = (
)
_UniffiLib.uniffi_janjacord_mobile_checksum_func_add_member.restype = ctypes.c_uint16
_UniffiLib.uniffi_janjacord_mobile_checksum_func_argon2id.argtypes = (
)
_UniffiLib.uniffi_janjacord_mobile_checksum_func_argon2id.restype = ctypes.c_uint16
_UniffiLib.uniffi_janjacord_mobile_checksum_func_create_group.argtypes = (
)
_UniffiLib.uniffi_janjacord_mobile_checksum_func_create_group.restype = ctypes.c_uint16
_UniffiLib.uniffi_janjacord_mobile_checksum_func_decrypt.argtypes = (
)
_UniffiLib.uniffi_janjacord_mobile_checksum_func_decrypt.restype = ctypes.c_uint16
_UniffiLib.uniffi_janjacord_mobile_checksum_func_encrypt.argtypes = (
)
_UniffiLib.uniffi_janjacord_mobile_checksum_func_encrypt.restype = ctypes.c_uint16
_UniffiLib.uniffi_janjacord_mobile_checksum_func_export_group.argtypes = (
)
_UniffiLib.uniffi_janjacord_mobile_checksum_func_export_group.restype = ctypes.c_uint16
_UniffiLib.uniffi_janjacord_mobile_checksum_func_generate_key_package.argtypes = (
)
_UniffiLib.uniffi_janjacord_mobile_checksum_func_generate_key_package.restype = ctypes.c_uint16
_UniffiLib.uniffi_janjacord_mobile_checksum_func_import_group.argtypes = (
)
_UniffiLib.uniffi_janjacord_mobile_checksum_func_import_group.restype = ctypes.c_uint16
_UniffiLib.uniffi_janjacord_mobile_checksum_func_join_group.argtypes = (
)
_UniffiLib.uniffi_janjacord_mobile_checksum_func_join_group.restype = ctypes.c_uint16
_UniffiLib.uniffi_janjacord_mobile_checksum_func_process_commit.argtypes = (
)
_UniffiLib.uniffi_janjacord_mobile_checksum_func_process_commit.restype = ctypes.c_uint16
_UniffiLib.uniffi_janjacord_mobile_checksum_func_remove_member.argtypes = (
)
_UniffiLib.uniffi_janjacord_mobile_checksum_func_remove_member.restype = ctypes.c_uint16
_UniffiLib.uniffi_janjacord_mobile_fn_func_add_member.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_janjacord_mobile_fn_func_add_member.restype = _UniffiRustBuffer
_UniffiLib.uniffi_janjacord_mobile_fn_func_argon2id.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_janjacord_mobile_fn_func_argon2id.restype = _UniffiRustBuffer
_UniffiLib.uniffi_janjacord_mobile_fn_func_create_group.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_janjacord_mobile_fn_func_create_group.restype = _UniffiRustBuffer
_UniffiLib.uniffi_janjacord_mobile_fn_func_decrypt.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_janjacord_mobile_fn_func_decrypt.restype = _UniffiRustBuffer
_UniffiLib.uniffi_janjacord_mobile_fn_func_encrypt.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_janjacord_mobile_fn_func_encrypt.restype = _UniffiRustBuffer
_UniffiLib.uniffi_janjacord_mobile_fn_func_export_group.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_janjacord_mobile_fn_func_export_group.restype = _UniffiRustBuffer
_UniffiLib.uniffi_janjacord_mobile_fn_func_generate_key_package.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_janjacord_mobile_fn_func_generate_key_package.restype = _UniffiRustBuffer
_UniffiLib.uniffi_janjacord_mobile_fn_func_import_group.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_janjacord_mobile_fn_func_import_group.restype = None
_UniffiLib.uniffi_janjacord_mobile_fn_func_join_group.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_janjacord_mobile_fn_func_join_group.restype = _UniffiRustBuffer
_UniffiLib.uniffi_janjacord_mobile_fn_func_process_commit.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_janjacord_mobile_fn_func_process_commit.restype = None
_UniffiLib.uniffi_janjacord_mobile_fn_func_remove_member.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.c_uint32,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_janjacord_mobile_fn_func_remove_member.restype = _UniffiRustBuffer

_uniffi_check_contract_api_version(_UniffiLib)
# _uniffi_check_api_checksums(_UniffiLib)



# Public interface members begin here.


class _UniffiFfiConverterString:
    @staticmethod
    def check_lower(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8_bytes = buf.read(size)
        return utf8_bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        utf8_bytes = value.encode("utf-8")
        buf.write_i32(len(utf8_bytes))
        buf.write(utf8_bytes)

    @staticmethod
    def lift(buf):
        with buf.consume_with_stream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()



# MlsError
# We want to define each variant as a nested class that's also a subclass,
# which is tricky in Python.  To accomplish this we're going to create each
# class separately, then manually add the child classes to the base class's
# __dict__.  All of this happens in dummy class to avoid polluting the module
# namespace.
class MlsError(Exception):
    """
    Erro exposto ao Kotlin/Swift (uniffi exige tipo de erro próprio, não String).
"""
    pass

_UniffiTempMlsError = MlsError

class MlsError:  # type: ignore
    """
    Erro exposto ao Kotlin/Swift (uniffi exige tipo de erro próprio, não String).
"""
    
    class Message(_UniffiTempMlsError):
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            if not isinstance(values[0], str):
                raise TypeError(f"unexpected type for tuple element 0 - expected 'str', got '{type(values[0])}'")
            super().__init__(", ".join(map(repr, values)))
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __repr__(self):
            return "MlsError.Message({})".format(str(self))
    _UniffiTempMlsError.Message = Message # type: ignore

MlsError = _UniffiTempMlsError # type: ignore
del _UniffiTempMlsError


class _UniffiFfiConverterTypeMlsError(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return MlsError.Message(
                _UniffiFfiConverterString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if isinstance(value, MlsError.Message):
            _UniffiFfiConverterString.check_lower(value._values[0])
            return

    @staticmethod
    def write(value, buf):
        if isinstance(value, MlsError.Message):
            buf.write_i32(1)
            _UniffiFfiConverterString.write(value._values[0], buf)

class _UniffiFfiConverterUInt32(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u32"
    VALUE_MIN = 0
    VALUE_MAX = 2**32

    @staticmethod
    def read(buf):
        return buf.read_u32()

    @staticmethod
    def write(value, buf):
        buf.write_u32(value)
def add_member(seed_hex: str,identity_id: str,group_id_hex: str,key_package_b64: str) -> str:
    
    _UniffiFfiConverterString.check_lower(seed_hex)

    _UniffiFfiConverterString.check_lower(identity_id)

    _UniffiFfiConverterString.check_lower(group_id_hex)

    _UniffiFfiConverterString.check_lower(key_package_b64)
    _uniffi_lowered_args = (
        _UniffiFfiConverterString.lower(seed_hex),
        _UniffiFfiConverterString.lower(identity_id),
        _UniffiFfiConverterString.lower(group_id_hex),
        _UniffiFfiConverterString.lower(key_package_b64),
    )
    _uniffi_lift_return = _UniffiFfiConverterString.lift
    _uniffi_error_converter = _UniffiFfiConverterTypeMlsError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_janjacord_mobile_fn_func_add_member,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def argon2id(password: str,salt_hex: str) -> str:
    """
    Argon2id (RFC 9106, v1.3, t=2, m=19456KiB, p=1, out 32) — mesmos parâmetros do
    desktop (noble-hashes) → hash idêntico. Roda nativo (RustCrypto) no celular,
    sem JS puro (Hermes) nem libs de terceiros no fluxo de identidade.
"""
    
    _UniffiFfiConverterString.check_lower(password)

    _UniffiFfiConverterString.check_lower(salt_hex)
    _uniffi_lowered_args = (
        _UniffiFfiConverterString.lower(password),
        _UniffiFfiConverterString.lower(salt_hex),
    )
    _uniffi_lift_return = _UniffiFfiConverterString.lift
    _uniffi_error_converter = _UniffiFfiConverterTypeMlsError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_janjacord_mobile_fn_func_argon2id,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def create_group(seed_hex: str,identity_id: str,group_id_hex: str) -> str:
    
    _UniffiFfiConverterString.check_lower(seed_hex)

    _UniffiFfiConverterString.check_lower(identity_id)

    _UniffiFfiConverterString.check_lower(group_id_hex)
    _uniffi_lowered_args = (
        _UniffiFfiConverterString.lower(seed_hex),
        _UniffiFfiConverterString.lower(identity_id),
        _UniffiFfiConverterString.lower(group_id_hex),
    )
    _uniffi_lift_return = _UniffiFfiConverterString.lift
    _uniffi_error_converter = _UniffiFfiConverterTypeMlsError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_janjacord_mobile_fn_func_create_group,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def decrypt(seed_hex: str,identity_id: str,group_id_hex: str,ciphertext_b64: str) -> str:
    
    _UniffiFfiConverterString.check_lower(seed_hex)

    _UniffiFfiConverterString.check_lower(identity_id)

    _UniffiFfiConverterString.check_lower(group_id_hex)

    _UniffiFfiConverterString.check_lower(ciphertext_b64)
    _uniffi_lowered_args = (
        _UniffiFfiConverterString.lower(seed_hex),
        _UniffiFfiConverterString.lower(identity_id),
        _UniffiFfiConverterString.lower(group_id_hex),
        _UniffiFfiConverterString.lower(ciphertext_b64),
    )
    _uniffi_lift_return = _UniffiFfiConverterString.lift
    _uniffi_error_converter = _UniffiFfiConverterTypeMlsError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_janjacord_mobile_fn_func_decrypt,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def encrypt(seed_hex: str,identity_id: str,group_id_hex: str,plaintext_b64: str) -> str:
    
    _UniffiFfiConverterString.check_lower(seed_hex)

    _UniffiFfiConverterString.check_lower(identity_id)

    _UniffiFfiConverterString.check_lower(group_id_hex)

    _UniffiFfiConverterString.check_lower(plaintext_b64)
    _uniffi_lowered_args = (
        _UniffiFfiConverterString.lower(seed_hex),
        _UniffiFfiConverterString.lower(identity_id),
        _UniffiFfiConverterString.lower(group_id_hex),
        _UniffiFfiConverterString.lower(plaintext_b64),
    )
    _uniffi_lift_return = _UniffiFfiConverterString.lift
    _uniffi_error_converter = _UniffiFfiConverterTypeMlsError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_janjacord_mobile_fn_func_encrypt,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def export_group(identity_id: str,group_id_hex: str) -> str:
    
    _UniffiFfiConverterString.check_lower(identity_id)

    _UniffiFfiConverterString.check_lower(group_id_hex)
    _uniffi_lowered_args = (
        _UniffiFfiConverterString.lower(identity_id),
        _UniffiFfiConverterString.lower(group_id_hex),
    )
    _uniffi_lift_return = _UniffiFfiConverterString.lift
    _uniffi_error_converter = _UniffiFfiConverterTypeMlsError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_janjacord_mobile_fn_func_export_group,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def generate_key_package(seed_hex: str,identity_id: str) -> str:
    
    _UniffiFfiConverterString.check_lower(seed_hex)

    _UniffiFfiConverterString.check_lower(identity_id)
    _uniffi_lowered_args = (
        _UniffiFfiConverterString.lower(seed_hex),
        _UniffiFfiConverterString.lower(identity_id),
    )
    _uniffi_lift_return = _UniffiFfiConverterString.lift
    _uniffi_error_converter = _UniffiFfiConverterTypeMlsError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_janjacord_mobile_fn_func_generate_key_package,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def import_group(identity_id: str,group_id_hex: str,group_state_b64: str) -> None:
    
    _UniffiFfiConverterString.check_lower(identity_id)

    _UniffiFfiConverterString.check_lower(group_id_hex)

    _UniffiFfiConverterString.check_lower(group_state_b64)
    _uniffi_lowered_args = (
        _UniffiFfiConverterString.lower(identity_id),
        _UniffiFfiConverterString.lower(group_id_hex),
        _UniffiFfiConverterString.lower(group_state_b64),
    )
    _uniffi_lift_return = lambda val: None
    _uniffi_error_converter = _UniffiFfiConverterTypeMlsError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_janjacord_mobile_fn_func_import_group,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def join_group(seed_hex: str,identity_id: str,welcome_b64: str) -> str:
    
    _UniffiFfiConverterString.check_lower(seed_hex)

    _UniffiFfiConverterString.check_lower(identity_id)

    _UniffiFfiConverterString.check_lower(welcome_b64)
    _uniffi_lowered_args = (
        _UniffiFfiConverterString.lower(seed_hex),
        _UniffiFfiConverterString.lower(identity_id),
        _UniffiFfiConverterString.lower(welcome_b64),
    )
    _uniffi_lift_return = _UniffiFfiConverterString.lift
    _uniffi_error_converter = _UniffiFfiConverterTypeMlsError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_janjacord_mobile_fn_func_join_group,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def process_commit(seed_hex: str,identity_id: str,group_id_hex: str,commit_b64: str) -> None:
    
    _UniffiFfiConverterString.check_lower(seed_hex)

    _UniffiFfiConverterString.check_lower(identity_id)

    _UniffiFfiConverterString.check_lower(group_id_hex)

    _UniffiFfiConverterString.check_lower(commit_b64)
    _uniffi_lowered_args = (
        _UniffiFfiConverterString.lower(seed_hex),
        _UniffiFfiConverterString.lower(identity_id),
        _UniffiFfiConverterString.lower(group_id_hex),
        _UniffiFfiConverterString.lower(commit_b64),
    )
    _uniffi_lift_return = lambda val: None
    _uniffi_error_converter = _UniffiFfiConverterTypeMlsError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_janjacord_mobile_fn_func_process_commit,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def remove_member(seed_hex: str,identity_id: str,group_id_hex: str,leaf_index: int) -> str:
    
    _UniffiFfiConverterString.check_lower(seed_hex)

    _UniffiFfiConverterString.check_lower(identity_id)

    _UniffiFfiConverterString.check_lower(group_id_hex)

    _UniffiFfiConverterUInt32.check_lower(leaf_index)
    _uniffi_lowered_args = (
        _UniffiFfiConverterString.lower(seed_hex),
        _UniffiFfiConverterString.lower(identity_id),
        _UniffiFfiConverterString.lower(group_id_hex),
        _UniffiFfiConverterUInt32.lower(leaf_index),
    )
    _uniffi_lift_return = _UniffiFfiConverterString.lift
    _uniffi_error_converter = _UniffiFfiConverterTypeMlsError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_janjacord_mobile_fn_func_remove_member,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)

__all__ = [
    "InternalError",
    "MlsError",
    "add_member",
    "argon2id",
    "create_group",
    "decrypt",
    "encrypt",
    "export_group",
    "generate_key_package",
    "import_group",
    "join_group",
    "process_commit",
    "remove_member",
]